apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-dynamic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-dynamic-app
  template:
    metadata:
      labels:
        app: configmap-dynamic-app
    spec:
      containers:
        - name: configmap-dynamic-app
          image: configmap-dynamic:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: app-config