spring.application.name=configmap
spring.cloud.kubernetes.config.enabled=true
spring.cloud.kubernetes.config.name=my-config
spring.cloud.kubernetes.config.namespace=default
spring.cloud.kubernetes.config.sources[0].name=my-config
spring.cloud.kubernetes.config.sources[0].namespace=default
spring.cloud.kubernetes.config.reload.enabled=true
spring.cloud.kubernetes.config.reload.strategy=refresh
server.port=8080