# application.properties ??
server.port=8082
management.endpoints.web.exposure.include=*

myValue=Legacy-Final-Test
jobCron=0 0 * * * *
static_message=This-Is-Static

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.main.allow-bean-definition-overriding=true
spring.sql.init.continue-on-error=true
spring.jpa.hibernate.ddl-auto=none

spring.task.scheduling.pool.size=5


logging.level.org.springframework.cloud.kubernetes.config.reload=DEBUG
logging.level.org.springframework.cloud.context.scope.refresh=DEBUG