spring.application.name=configmap-dynamic
server.port=8082

# ??? ????? ??
management.endpoints.web.exposure.include=refresh,health,info

# ?? ????: ??? configtree + ????? configmap (?? ??)
spring.config.import[0]=optional:configtree:/config/
spring.config.import[1]=optional:kubernetes:configmap:app-config

myValue=test-value
jobCron=0 0 * * * *
# Kubernetes Secrets ?? ?? (?? ? true? ??)
spring.cloud.kubernetes.secrets.enabled=false

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

spring.main.allow-bean-definition-overriding=true

spring.sql.init.continue-on-error=true
spring.jpa.hibernate.ddl-auto=none